### ISSUE TITLE
Training new dataset

### ISSUE THREAD

**Issue by FlyingRoastDuck** [vana77/Bottom-up-Clustering-Person-Re-identification#1]
Hi, I have a question about using your code to train my own dataset. It seems that Market dataset you provide has been preprocessed, so I just want to know how to write dataloader to process my own dataset. Could you please tell me the exact meaning of  "video_id" in [market1501.py?](https://github.com/vana77/Bottom-up-Clustering-Person-Re-identification/blob/master/reid/datasets/market1501.py#L69) Thank you.

**Comment by vana77** [comment]
Hi @FlyingRoastDuck ,
Video_id is the index of each training image/video. Suppose there are 12936 training images in market-1501, then video_id is supposed to be [0,12935].

**Comment by jpainam** [comment]
Hi, thank you for the code,
i find it difficult to understand the structure of your preprocessed market1501 dataset. Pls, kindly you give detailed about the expected structure of `dataset_all` in 
```python 
dataset_all = datasets.create(args.dataset, osp.join(args.data_dir, args.dataset))
```
thank you
