### ISSUE TITLE
Different expected number in model.forward and what's the futures in your training stage and testing stage?

### ISSUE THREAD

**Issue by justopit** [vana77/Bottom-up-Clustering-Person-Re-identification#10]
I found that  the number of output in your model class End2End_AvgPooling is 1. However, the expected output number in your evaluate and parse function is 2. In addition, in training state, it seems the feature of an image is not normalized , just according to your model class. However, your cluster center is normalized. 
If I can get your reply, I would be grateful.

**Comment by vana77** [comment]
Hi @justopit ,
1. If you output the returned data you will find that the one output is combined by two components, which is returned by AvgPooling.
2. You can try if it works better when doing normalization.

**Comment by justopit** [comment]
@vana77 Thank you!!!
