### ISSUE TITLE
why the rank-1 of DukeMTMC-reID  is 44.5?

### ISSUE THREAD

**Issue by leileiaixiaoqiang** [vana77/Bottom-up-Clustering-Person-Re-identification#13]
hello:
    i have tested the code ,but i've a better performance of  DukeMTMC-reID,you can see the result in the pic,Did I do sth wrong?
![Uploading 1571587472(1).png…]()

**Comment by vana77** [comment]
Hi @leileiaixiaoqiang , I can't see your pic. I just cloned and ran the code and got rank1 = 40.8, mAP = 23.1. Did you use the updated code? We just found a bug and fixed it, which leads to a performance drop on DukeMTMC-reID.

**Comment by leileiaixiaoqiang** [comment]
hi,@vana77 ,yes, i am using the updated code,I just revised  from self.later_steps = 2  to  self.later_steps = 5,then i got  the result like this:
![1571735583(1)](https://user-images.githubusercontent.com/18694111/67272492-38ded700-f4ef-11e9-8750-1037d817883b.jpg)
Can you help me to check it ?thanks!

**Comment by vana77** [comment]
Hi @leileiaixiaoqiang, that's curous. I can only get rank-1 = 38.6 and mAP = 19.9 when I set later_steps to 5. Could you please send the log to me? My email: yutian.lin@student.uts.edu.au

**Comment by leileiaixiaoqiang** [comment]
hi @vana77 i've already sent the logs to you ,please check your mailbox.thx!
