### ISSUE TITLE
关于MARS数据集的处理

### ISSUE THREAD

**Issue by Zvenger** [vana77/Bottom-up-Clustering-Person-Re-identification#23]
请问一下，MARS数据集你是怎么处理的？我之前是做监督的Video reid的，我想做一下无监督的。发现这个Mars数据集的设置和有监督的不太一样。我看了下train gallery query的数据都是一样的，但是为什么要专门设置gallery_split 的id从999开始呢？直接使用原始数据集给定的标签有什么不妥吗？十分感谢。

**Comment by vana77** [comment]
@Zvenger 源数据集train和gallery的标签是混着的，当时为了方便处理，把数据集做了重新映射，训练集1~625，测试集999~1634。直接使用原始数据集给定的标签也完全没问题。

**Comment by vana77** [comment]
@Zvenger 源数据集train和gallery的标签是混着的，当时为了方便处理，把数据集做了重新映射，训练集1到625，测试集999到1634。直接使用原始数据集给定的标签也完全没问题。

**Comment by Zvenger** [comment]
好的，十分感谢。
