### ISSUE TITLE
Can't reach 61% in the market as in the paper

### ISSUE THREAD

**Issue by momoshuaiqiang** [vana77/Bottom-up-Clustering-Person-Re-identification#25]
Hello, I run the code you uploaded directly. Rank-1 on the market is 55.8%, which is different from 61% in the paper. Is there any special Super parameter to set? I would like to quote your code and paper in my paper. Wish for your rely.
你好,我直接运行您上传的代码，在market上rank-1为55.8%,与论文中的61%不同，请问是否有特殊的超参数要设置？我想在自己的论文中引用您的代码和论文。期待您的回复。

**Comment by vana77** [comment]
你好，我昨天用直接拉下来的代码跑了一遍，可以复现rank-1 61%，所有参数、代码都没改。我也不确定为什么你跑起来会有问题。log文件见附件可作为参考。
________________________________

**Comment by momoshuaiqiang** [comment]
谢谢您的回复，我昨天重新配置环境和下载代码，可以跑出您github中所描述的61%的精度了。还有一个疑问，论文中描述market能够跑到66%（加了正则化以后）。但代码中加了正则化却只跑到61%,请问是需要某些超参数的调整吗？（因为我想引用您的论文和复现代码，所以想问清楚下，再次感谢您能够开源代码。）

**Comment by vana77** [comment]
可以看代码readme中的描述，在aaai发表版本我们在Market上得到了结果66.2%。然而后来我们发现代码中memory是由上一次cluster结果初始化的，从而导致memory和cluster的错位。由于没有shuffle训练数据，这种错位反而会无意中利用到相邻数据属于同一个行人的信息，导致在Market，Duke，MARS数据集上结果偏高，而在DukeVideo上结果偏低。在修正了这个bug后，Market可以达到61%。我们重跑实验更新了论文中的实验部分，更新的论文参见代码主页链接。带来了困扰很不好意思，引用实验结果请以更新后的结果为准，谢谢。
https://vana77.github.io/vana77.github.io/images/AAAI19.pdf
________________________________

**Comment by momoshuaiqiang** [comment]
我明白了，十分谢谢您严谨的科学态度及回复。

**Comment by zhaiyutong** [comment]
> Hello, I run the code you uploaded directly. Rank-1 on the market is 55.8%, which is different from 61% in the paper. Is there any special Super parameter to set? I would like to quote your code and paper in my paper. Wish for your rely.
> 你好,我直接运行您上传的代码，在market上rank-1为55.8%,与论文中的61%不同，请问是否有特殊的超参数要设置？我想在自己的论文中引用您的代码和论文。期待您的回复。

你好，请问你运行的时候有出现下面这两个报警吗？
1. The sklearn.metrics.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.

2. UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. 

能麻烦你告诉一下我，你sklearn和pytorch的版本吗
