### ISSUE TITLE
The version of scikit-learn and metric learn

### ISSUE THREAD

**Issue by zhaiyutong** [vana77/Bottom-up-Clustering-Person-Re-identification#26]
作者你好，非常感谢你提供了开源的代码！
我git clone了你的代码，并且下载了Market1501放在了data文件夹下，然后直接用了sh ./run.sh来跑代码。
但是terminal端的结果一直不收敛，请问想要实现你的效果，是还需要调整什么参数吗？
ps： h5py, scikit-learn, metric-learn, tqdm的版本可以贴一下吗？
非常感谢！

Hello author, thanks so much for the open source code!
I git clone your code and downloaded Market1501 and put it in the data folder. And then just ran the code with sh . /run.sh to run the code.
But the results on the terminal side never converge, is there any parameter that needs to be adjusted to achieve your effect?
ps: h5py, scikit-learn, metric-learn, tqdm's Can you post the version?
Thank you very much!

**Comment by zhaiyutong** [comment]
I have encountered two warnings when I run your code
1. FutureWarning: The sklearn.metrics.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
2. UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

**Comment by vana77** [comment]
你好，参数不需要修改，估计是环境版本问题。我用的版本如下，可作为参考：
pytorch 1.0.1.post2
Sklearn 0.19.2
tqdm 4.47.0
h5py 2.7.1
________________________________

**Comment by zhaiyutong** [comment]
> 你好，参数不需要修改，估计是环境版本问题。我用的版本如下，可作为参考： pytorch 1.0.1.post2 Sklearn 0.19.2 tqdm 4.47.0 h5py 2.7.1
> […](#)
> ________________________________ From: zhaiyutong <notifications@github.com> Sent: Thursday, July 9, 2020 1:10 AM To: vana77/Bottom-up-Clustering-Person-Re-identification <Bottom-up-Clustering-Person-Re-identification@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [vana77/Bottom-up-Clustering-Person-Re-identification] 复现的效果不收敛，percision大多数是0 (#26) 作者你好，非常感谢你提供了开源的代码！ 我git clone了你的代码，并且下载了Market1501放在了data文件夹下，然后直接用了sh ./run.sh来跑代码。 但是terminal端的结果一直不收敛，请问想要实现你的效果，是还需要调整什么参数吗？ ps： h5py, scikit-learn, metric-learn, tqdm的版本可以贴一下吗？ 非常感谢！ ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://protect-au.mimecast.com/s/NaOTC4QOq5s767m8fOCjsW?domain=github.com>, or unsubscribe<https://protect-au.mimecast.com/s/nqXjC5QPr6sWRWxlHOcq2j?domain=github.com>.

你好，谢谢你的回复
我后来找到了问题所在，是因为我跑你代码的实现，直接调用了8个GPU，所以收敛的非常慢，我觉得你可以在你的代码里加上训练时GPU参数的设置，谢谢！

**Comment by Jacobxz** [comment]
你好,我换market数据集，提示错误：
NotADirectoryError: [Errno 20] Not a directory: '/home/lab/dataset/market1501/bounding_box_train/0002_c1s1_000451_03.jpg'

请问要修改market.py代码吗
