### ISSUE TITLE
RuntimeError: DataLoader worker (pid 18591) is killed by signal: Killed.

### ISSUE THREAD

**Issue by Mickeybaby** [vana77/Bottom-up-Clustering-Person-Re-identification#5]
When I train on  DukeMTMC-VideoReID datasets，this error will be displayed.
When batchsize is seted to 16,error termination at the fifth epoch.
When I set batchsize to 12，error termination at the 18th epoch.
I dare not adjust batchsize any more, because I don't know how to set lr.
Can you give me some advice?

**Comment by vana77** [comment]
Hi @Mickeybaby , I think it's because there is no enough memory in your cpu/gpu. I remember that I got this error when evaluating the video datasets, so that I change the batchsize to 1 when testing. You might check the exact line the the error is reported.

**Comment by Mickeybaby** [comment]
@vana77 
Thanks.I will try it.
Best wishes!
