### ISSUE TITLE
About paper and code

### ISSUE THREAD

**Issue by Mickeybaby** [vana77/Bottom-up-Clustering-Person-Re-identification#6]

**Comment by vana77** [comment]
Hi @Mickeybaby,

In reid/bottom_up.py,

`cnt = torch.FloatTensor([ len(label_to_images[label[idx]]) for idx in range(len(u_feas))])`
For each training image, this line counts the number of samples in the cluster that the training image belonging to.

`dists += ratio_n * (cnt.view(1, len(cnt)) + cnt.view(len(cnt), 1))`
In line 190, (cnt.view(1, len(cnt)) + cnt.view(len(cnt), 1)) calculates |A| + |B|.

**Comment by Mickeybaby** [comment]
@vana77 Thank you so much!
Best wishes!
