### ISSUE TITLE
About code and paper

### ISSUE THREAD

**Issue by Mickeybaby** [vana77/Bottom-up-Clustering-Person-Re-identification#7]
Hello, thank you for your great work, which has benefited me a lot.
I am a beginner in computer and reID.I want to ask you some questions about the paper and the code.Thank you for taking time out of your busy schedule to answer my questions！
1、In section3.2 of the paper，Vy = 1/2（Vy + v）
What is the basis of this formula？I don't know why you update lookup table V like this.
2、In section 3.2 of the paper,
"d(xa,xb) is deﬁned as the Euclidean distance between the feature embeddings of two images, i.e., va and vb. Speciﬁcally, d(xa,xb) = ||va −vb||." 
Here's the Euclidean distance.But why use this formula“dists.addmm_(1, -2, x, y.t()）” to calculate distance in code?I don't know the connection between the two.
3、In section 3.2 of the paper，
Where does τ in Formula （2）represent in the code.
These are my questions.I'm sorry to take up your time to answer my questions.But as a beginner, I really want to figure out these questions.
Best wishes  to you!
祝您一切顺心，生活幸福美满！

**Comment by vana77** [comment]
1. There are many ways to uptate the lookup table, we choose to calculate the average of the old one and the new feature, and you can try other strategies.
2. It‘s a fast way to calculate Euclidean distance. You can find a illustration here: https://blog.csdn.net/weixin_44538273/article/details/88409198
3. In exclusive_loss.py line 36: 
`outputs = Exclusive(self.V)(inputs, targets) * self.t`
    In bottom_up.py line 69: 
`self.criterion = ExLoss(self.embeding_fea_size, self.num_classes, t=10).cuda()`

**Comment by Mickeybaby** [comment]
Thank you for your careful guidance！I'm grateful.
But on the third question, I still have a few questions.
The value of t in the code is 10, but it is set to 0.1 in the paper.
I don't know because I haven't understood it thoroughly yet.
Best wishes！

**Comment by vana77** [comment]
In paper, the formula is /0.1, and in the code the fomula is *10.

**Comment by Mickeybaby** [comment]
It suddenly dawned on me. Thank you very much！

**Comment by zwyyy215** [comment]
Hello, I want to ask you a question. After the model comes out, two kinds of features are retained, one is only through the pooling layer, the other is through the FC layer, but when I look at the code, I feel that all the features used are through the FC layer, so I want to ask why the features only through the pooling layer should be saved by variables alone.
I think it's meaningful that you keep the features that only pass through the pooling layer, but I'm foolish enough to fail to understand them.
