### ISSUE TITLE
What does the variable video_id in reid class dataset mean?

### ISSUE THREAD

**Issue by justopit** [vana77/Bottom-up-Clustering-Person-Re-identification#8]
What does the variable video_id in reid class dataset mean?The number of images on  same   identity and same camera?

**Comment by vana77** [comment]
Hi @justopit , for video datasets, it counts the number of tracklets (one tracklet consists of several images). For image based datasets, it counts the number of images. For example the video_id for Market-1501 is 0 to 12935.

**Comment by justopit** [comment]
> Hi @justopit , for video datasets, it counts the number of tracklets (one tracklet consists of several images). For image based datasets, it counts the number of images. For example the video_id for Market-1501 is 0 to 12935.

Thank you very much for your answer
