### ISSUE TITLE
DukeMTMC-VideoReID can't be download

### ISSUE THREAD

**Issue by moodom** [vana77/Bottom-up-Clustering-Person-Re-identification#9]
Hi，thanks for your work and I benefit a lot from it. Recently, I find  that I can't download the dataset DukeMTMC-VideoReID. can you share it with me in Baidu Yun?  Thank you very much.

**Comment by vana77** [comment]
Hi @moodom, I'm so sorry, but the authors of the original DukeMTMC dataset have withdrawn their dataset because of the privacy problem so that I can not distribute the dataset anymore.
